# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - Windows-2019
        - macOS-12
        - macOS-latest
        - Ubuntu-20.04
        - Ubuntu-22.04
        go:
        - 1.17
        - 1.18

      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...
